### ISSUE TITLE
Labels feature

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1462]
**Describe the bug**
Right now there's less clarity between tags and labels and how to use it.

**Changes**

- Remove assign tag option
- Hide tags sections from side panel.
- Show labels with messages on chat screen (we can go with default color for now and maybe allow label colors when we build label management)
- Advanced search: includes labels instead of include tags
- Search results: show labels section instead of tags but works like tags
- Hide contact tags

Next phase: Build a central labels management screen

**Comment by shreesh1993** [comment]
- [ ] Remove assign tag option
- [ ] Hide tags sections from side panel.
- [ ] Show labels with messages on chat screen (we can go with default color for now and maybe allow label colors when we build label management)
- [ ] Advanced search: includes labels instead of include tags
- [ ] Search results: show labels section instead of tags but works like tags
- [ ] Hide contact tags
