### ISSUE TITLE
Continue when no response

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1540]
**Describe the bug**
Since there's no continue when there's no response for interactive messages. the message just keeps going endlessly.

![image](https://user-images.githubusercontent.com/16714604/125934624-68560ab0-b8ca-4b94-8102-b3058b814897.png)

check this chat: https://cc.tides.coloredcow.com/chat/780

**Comment by mdshamoon** [comment]
@abhi1203 continue when there is no response option is available when we wait for the end-user to send a message. This node sends an interactive message from the Glific end and is similar to send message node. 

The message going endlessly is fixed by the backend team. Please confirm if it's fixed now.

**Comment by abhi1203** [comment]
It's working. Thank you.
