### ISSUE TITLE
Make English as a default option for interactive messages

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1687]
**Is your feature request related to a problem? Please describe.**
There is no indicator on the edit form, which tells which language the user is creating an interactive message in. By default, the Bengali Language is selected and user adds content in English and tries to test it in English langauage

**Describe the solution you'd like**
Please make English the default language as it is in Flow editor to avoid confusion.

**Describe alternatives you've considered**
We can think of a dropdown of a language to select at the top so that the user doesn't get confused, which language the user is editing. Like in HSM templates.

<img width="1205" alt="Screenshot 2021-10-05 at 11 49 19 AM" src="https://user-images.githubusercontent.com/16541548/135971346-5f276e67-254d-46c2-857e-c7a6234b7a22.png">

**Comment by abhi1203** [comment]
@mohitsharma-22 the dark one is the selected language. If that's not clear, @mdshamoon let's use the dull grey-green color we have in other places to show that that's the selected language. 
This right now works similar to the floweditor screen where you can select the language on the top and enter content for that.
![image](https://user-images.githubusercontent.com/16714604/136001354-03ed16d8-fe1b-46f5-9c36-47359a241d2c.png)

The first language that a user saves becomes the default for that interactive message. But we need to change the order so that English always shows first. @mdshamoon 

We're not going with dropdown, and will change dropdown to this format in HSM also.
