### ISSUE TITLE
Simulator doesn't start the flow and doesn't show the response some times.

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1905]
**Describe the bug**
1. Click on the Preview button doesn't start the flow every time. The user has to close the simulator and open it again.
2. The responses on the simulators are not shown. It seems the simulator is stuck. and sometimes if the user closes the simulator and opens it again, then all the responses are shown.

**Screenshots**
Screenshots shared from Enable India 
<img width="929" alt="Screenshot 2022-02-09 at 12 03 15 PM" src="https://user-images.githubusercontent.com/16541548/153139862-27ef8e61-fded-4560-a777-424d94502d85.png">

**Comment by mdshamoon** [comment]
Added a possible fix for this and added some logs to look into the issue. 
Keeping the issue open to track if it persists.

**Comment by mdshamoon** [comment]
As discussed adding a warning popup if the websocket fails so that the user is aware that the websocket is connecting.

**Comment by mdshamoon** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/16714604/155133929-3c66bb46-35ef-4430-96a9-c3abf0fa6367.png">
We can go ahead with this UI and the following messages:

Sorry! Connection to server failed. Please refresh page to continue working.

Sorry! Unable to show live messages. Please refresh page.

**Comment by mdshamoon** [comment]
Added warnings when connection breaks but it is breaking too often. After reading this issue maybe we can change the package for handling websockets in the backend.
https://github.com/absinthe-graphql/absinthe-socket/issues/53
We are using this package for absinthe subscriptions which is not maintained and may have issues with the latest apollo client. They have suggested to use this library instead

https://github.com/geometerio/absinthe_graphql_ws
so that we have direct support for apollo subscriptions using apollo-link-ws and not use the phoenix.js layer in between.
