### ISSUE TITLE
Not able to open the flow in editor

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1923]

**Comment by mohitsharma-22** [comment]
Reap Benefits Flow is showing a blank screen while opening in flow editor.

<img width="850" alt="Screenshot 2022-02-18 at 12 14 28 PM" src="https://user-images.githubusercontent.com/16541548/154632069-ba2a0782-4c62-4484-a2a4-c34f8111ff8c.png">

**Comment by mdshamoon** [comment]
@mohitsharma-22 I have fixed this issue. It is caused by using the reserved words in floweditor: `Other` and `All Responses` as category name. The floweditor does not handle this very well. I will create an issue in the original floweditor as well so that they fix this issue.

Meanwhile you can also suggest NGOs to not use Other and All Responses as category names as they are already defined.
