### ISSUE TITLE
HSM unknown error

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#2216]
**Describe the bug**
Getting this error: 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/16714604/200549725-612c533a-3170-4595-9133-928ee3566f9f.png">
Even the content is not getting populated int he simulator:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/16714604/200549762-76be954d-d400-42f8-9ea2-5bc22a778844.png">

**To Reproduce**
I used this content for the HSM:
Lang: English
Title: F2G1_01
Message: Hi {{1}}! 👋  I’m back again for another week of fun and learning! 😁 💫
Sample: Hi [Suraj]! 👋  I’m back again for another week of fun and learning! 😁 💫
Button: Hi Ikki! 👋
Category: Transactional
Element name: week_start
Attachment type: Sticker
Attachment URL: https://storage.googleapis.com/ikki_assets/Visual%20Assets/Stickers/Ikki%20Stickers/Ikki_g0_stk.webp

**Comment by mdshamoon** [comment]
@abhi1203 as for the content not shown, it is because captions are not supported with stickers. So only the sticker is shown.

For the error, I am not able to see a proper error in this case but based on previous experiences in stickers it seems the size of the sticker is not correct. These are the guidelines for a sticker on whatsapp

<img width="514" alt="image" src="https://user-images.githubusercontent.com/32592458/200753668-614d6bbe-b4ad-4dd6-ac1c-87762520c8ac.png">

**Comment by mdshamoon** [comment]
@pankaj-ag do you know if we support sticker in an HSM. I can't find any documentation for that

**Comment by mdshamoon** [comment]
This will be be taken care in #2223
