### ISSUE TITLE
Notifications for Low Wallet Balance

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2448]
**Is your feature request related to a problem? Please describe.**
Low Wallet Balance notifications

**Describe the solution you'd like**
Ability to configure the limit at which low balance notifications needs to be triggered. Glific admin will have the ability to set an amount at which alert needs to be made.

**Describe alternatives you've considered**
none

**Additional context**
Was raised during sprint as well as Delhi city meetup

**Comment by AkhileshNegi** [comment]
We have added support for the same in the backend and based on our discussion in the developer call rather than adding it in frontend for now, we'll configure it from the backend for NGOs needing it.
As adding in frontend and NGO configuring it, the usage will be fairly low to change configuration balance
https://github.com/glific/glific/pull/2975
