### ISSUE TITLE
No option to 'go back' in nodes having multiple tabs

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2458]
**Is your feature request related to a problem? Please describe.**
In the nodes having multiple tabs like Send the contact a message, Send staff member a message, Call a webhook, Start somebody else in a flow, Split by intent etc, there is no option to go back to node configuration whenever you click on 'Cancel'. Cancel simply exits the node pop up, so if some data was already populated in the node configuration screen, it will be lost. Also, it takes a toll on the user experience.

**Describe the solution you'd like**
There are two ways in which it could be solved :
1. Add a back button along with cancel and okay buttons.
2. On clicking 'Cancel', it should go back to the node configuration pop up were the already entered data is present.

**Describe alternatives you've considered**
Alternative solutions already mentioned
**Additional context**

**Comment by mdshamoon** [comment]
That is kind of an intended way for user to make a valid node before moving forward. The data that is put in different tabs always have some validations which are triggered when we press Okay button.

Taking a case when we have the back button
Suppose a user has some partially filled data in tabs which is not valid and user pressed the back button. Now they are trying to run the flow but getting weird errors that we can't predict because the validations did not acted upon them when the node was closed.

**Comment by aravind-glific** [comment]
Can't we can show a validation error when the user clicks on 'back button' without filling up the required details?

**Comment by mdshamoon** [comment]
That's what happens when you click on Ok button. If you do that then the functionality of Okay and back button is the same.
