### ISSUE TITLE
Things remaining in the new UI

### ISSUE THREAD

**Issue by mdshamoon** [glific/glific-frontend#2611]
**Describe the task**
Things remaining in the new UI

Design link: https://www.figma.com/file/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?node-id=2%3A2649&mode=dev

- [x] #2654
- [x] Sync him button should not full screen
- [x] Autocomplete filter width is not proper
- [x] Search bar lacks clarity
- [x] On Chat screen add limits for speed sends, templates and interactive messages. Right now they open all
- [x] Fix registration page
- [x] Fix borders of input
- [x] Fix button borders
- [x] #2655
- [x] Autocomplete style fixes
- [x] #2656
- [x] New design for registration page
- [x] Collection contacts edit delete popup not good
- [x] Chat message should have details at bottom
- [x] #2657
- [x] NGO main account should have hidden edit delete
- [x] #2658
- [x] #2659
- [x] #2660
- [x] #2661

**Comment by radhikaT4D** [comment]
@mdshamoon I was playing around with the github fields, feel free to change what I set. Also since we don't have the next week priorities yet, it got assigned to current and I can't change it :) 

Can you help look at the pending work, and estimate the time needed. we should try to assign a target date for release based on your estimates. Here's an example on how I would calculate the target date. 

ex: So if estimate is 10 dev-days for the work pending, with 50% of your bandwidth, 25% of Kurund's, and 20% buffer, the actual days would be (100/75*10*1.20) 16 days (thats 3-3.5 weeks).  So if you pick up this work next week, target dev complete date can be 27th Dec.  3 days for testing and bug fixing, release can be on Jan-2nd (considering away holidays).

Can you add a dev complete target date by adjusting the numbers above?  As a team we should be dev complete on that date.

**Comment by akanshaaa19** [comment]
- [ ]  In the side panel the `back` button is in small case
- [ ]  Tags tab is not there after Contact variable in the side panel
- [ ]  there is no space between the search bar and the next component in `/chat saved searches`
- [ ]  there is a triangle pointing upwards in the search bar in `saved searches`
- [ ]  in the Figma file, there is an info icon beside `Contact Profile`
- [ ]  in the `contact profile section`, there are two scroll bars for two different components
- [ ]  `clear conversation modal` text has different text alignments
- [ ]  in `templates, select variables` for the message. There is no spacing between text and input
- [ ]  `Add a new flow and edit a flow` checkboxes have extra spacing
- [ ]  `Add a new flow` tags dropdown takes only one input
- [ ]  `Flows / Interactive messages/triggers` table header actions tab is not aligned like others and there’s no gray background for the action buttons like in figma
- [ ]  `Add a new Interactive message` checkbox has extra spacing
- [ ]  there are two radio buttons in the figma file in `Add a new Interactive message`
- [ ]  `Add a new HSM Template` textareas have scrollbar
- [ ]  there is an active checkbox in the figma file in `Add a new Interactive message`
- [ ]  `Quick tools → searches` missing ellipsis under action header
- [ ]  `Notifications` has extra spacing on left side of radio buttons
- [ ]  When opening a collection there is no space between the two parts of the description
- [ ]  `Organization flows` has extra spacing between components

- [ ]  there are no placeholders for the following dropdowns
    - [ ]  select a flow dropdown in start a flow modal
    - [ ]  add contact to collection dropdown
    - [ ]  Add attachments to message type
    - [ ]  Select variables for the message dropdown
