### ISSUE TITLE
Automated Flow Tester : Warning - Flow/ Contact variable might be named incorrectly

### ISSUE THREAD

**Issue by aravind-glific** [glific/glific-frontend#2645]
- Whenever a variable inside 'send a message' node is named incorrectly, the text is displayed as such (Eg : @results.incorrectname)

- Show a warning whenever a variable is named incorrectly/ variable is named similar to a flow/ contact variable, but does not exactly match. Showing a dropdown of existing flow/ contact variables would help. 
- The warning could be shown right at the time of node creation, instead of showing it during the time of Publishing
- If the warning is shown at the time of Publishing, highlighting the node which is error prone would be good UX

**Comment by mdshamoon** [comment]
@aravind-glific the following variables can be used in a flow:

- Flow: 
  - @flow.id
  - @flow.name
- Calendar
  - @calendar.current_date
  - @calendar.yesterday
  - @calendar.tomorrow
  - @calendar.current_day
  - @calendar.current_month
  - @calendar.current_year
- Contact
  - @contact.fields.<variable name>
  - @contact.<contact details>
- Results
  - @results.parent.<variable name> 
  - @results.child.<variable name>
  - @results.<variable name>
- Global
  - @global.<variable name> 


I think in this case specifically we want to check for result variables and contact field variables if they are present or not.
We will plan this for only send message node for now and will check if the contact/result variable is valid or not. 
In case its invalid it gives an error on the node and doesn't allow it to save the node.

Also note that result variables can also come from webhooks in which case its not possible to check the presence of nested attributes like @result.gender.is_male. Since the attribute is_male will not be known to us until the webhook call succeeds we can't determine if the variable is correct or not.

Also its not possible to check for parent and child results since that will be known only at run time.

**Comment by mdshamoon** [comment]
Also dropdowns for some variables are not coming like @flows and @calendar. So will have to check as well. Creating a separate issue for that.
