### ISSUE TITLE
Moving message subscription logic to a higher order component?

### ISSUE THREAD

**Issue by rathorevaibhav** [glific/glific-frontend#454]
**Describe the task**
Currently, the logic for the subscription of a message is written in the chat component. So if we move out of that component we do not receive any message updates on any other screen.

**Expected behavior**
We can move this logic to a HOC so that we get notified of a new message on the whole application. We will receive message updates even when we are on any screen other than chat.

**Comment by kurund** [comment]
@rathorevaibhav Yes, I agree. It was in my list of things to do in 0.4 :) Not only subscription but the entire logic of conversations management should be moved out. We should move it to the service instead of HOC. Everyone just calls the service and get the required information and also update the same using subscription.
