### ISSUE TITLE
Speed send & template could not be created with the same title.

### ISSUE THREAD

**Issue by DigneshGujarathi** [glific/glific-frontend#460]
**Describe the bug**
I am not sure if this use case will or will not occur in real-time. 
Speed send & template could not be created with the same title. 
Consider, the scenario where we have the speed send "Test" and I'm trying to create a template with the title "Test". It will display an error that "Title already exists", but will not be shown in the template listing.

**Comment by abhi1203** [comment]
@DigneshGujarathi this is a good observation. My thought for this is that since HSM and speed send are always in different buckets, it may not be a great thing to reserve the title, one for another. While the use case you presented makes sense, displaying error might confuse the users because they never created a `speed send` with that particular title or vice versa. 

I feel it's a 50/50 chance, so maybe we can let users tell us if this is causing a problem and we can take action based on that and defer the task to that time? What do you think?

**Comment by kurund** [comment]
Yes agree with @abhi1203 closing this for now.
